### ISSUE TITLE
Mix up with 127.0.0.1 and localhost is caused Persona login to fail

### ISSUE THREAD

**Issue by sylvestre** [mozilla/nucleus#14]
The step by step documentation mentions 127.0.0.1:
https://media.readthedocs.org/pdf/nucleus/latest/nucleus.pdf
while the default configuration mentions localhost:
BROWSERID_AUDIENCES = ['http://localhost:8000']

On my local install, it is failing with:

```
06:39:1409578762 django_browserid.urls:INFO Loading BROWSERID_VERIFY_CLASS failed: Setting BROWSERID_VERIFY_CLASS not found..
```

Using localhost instead of 127.0.0.1 in my web browser fixes the issue.

**Comment by jgmize** [comment]
We are no longer using persona; closing old issue.
