### ISSUE TITLE
 Move dependency management to pip-compile-multi

### ISSUE THREAD

**Issue by stevejalim** [mozilla/nucleus#603]
### Description
As part of standarising how we manage our Python deps across MEAO, we're moving to [pip-compile-multi](https://pip-compile-multi.readthedocs.io/en/latest/)

### Key tasks

- [ ] Revamp dependency management tooling from `pip` to `pip-compile-multi`
- [ ] Expand Docker setup to allow for a two builds: Dev/`test`/local-dev build, and a `release` build, the same as with Bedrock

### Success critera
- [ ] CI passes
- [ ] No regression in behaviour/functionality
- [ ] Documentation is updated
- [ ] Separate documentation site can still be built 
- [ ] Project can be installed locally with no impediments

**Comment by stevejalim** [comment]
@robhudson Would you be interested in picking up ths one, based on what I've done in https://github.com/mozmeao/basket/pull/786 and https://github.com/mozilla/bedrock/pull/11176 ? If not, I'm happy to pick it up 👍

**Comment by robhudson** [comment]
Yeah I'll take it.
