### ISSUE TITLE
Dark-mode preference in user browser makes Django Admin hard to read 

### ISSUE THREAD

**Issue by stevejalim** [mozilla/nucleus#631]
With Django 3.2, the Admin invokes a dark CSS theme from the user's browser preference ([Release notes](https://docs.djangoproject.com/en/3.2/releases/3.2/#minor-features)).

However, with Nucleus, when dark mode is active, the editing UI becomes hard to read, at least in some situations

Eg, on `/admin/rna/note/789067/change/`with FF Dark Theme enabled:

<img width="1066" alt="Screenshot 2022-05-17 at 13 51 17" src="https://user-images.githubusercontent.com/101457/168815530-a0c6951b-a31c-4197-88db-5e620f1e5ed4.png">

And with a light theme enabled:

<img width="1512" alt="Screenshot 2022-05-17 at 13 51 26" src="https://user-images.githubusercontent.com/101457/168815543-016bb6ba-7be4-4a9c-be32-1f77f2ef506d.png">

On a quick look, there don't appear to be any custom Admin CSS in the project.

Might be that the simplest fix is to some custom CSS (Admin Media) to override that dark-mode support, or we do a little custom theming work - [docs here](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#admin-theming)

# Success criterion

- Regardless of whether the user has a dark theme or light theme enabled, the UI is consistently readable.

**Comment by dsmithpadilla** [comment]
+1 This makes nucleus really difficult to use at night or with any custom/dark theme. The Relman team most of the time has to force pick a light setting in order to add any notes/releases comfortably. Would really benefit from a fix 🙏 .

**Comment by stevejalim** [comment]
Thanks for the prompt @dsmithpadilla - am seeing how quickly one of us can get this sorted. Sorry to hear it's impacting your team's workflow

**Comment by stevejalim** [comment]
@dsmithpadilla I've got a fix in PR (see link above), but I'll hold of deploying it until after the next Fx release. It's not controversial or likely to cause problems, but _just in case_ :) Next time around, thought, your team won't need to flip into light mode - the site will remain in light mode regardless of OS or browser setting, like it used to do

**Comment by stevejalim** [comment]
Reopening this for visibility until it hits production

**Comment by stevejalim** [comment]
@dsmithpadilla OK the 'keep the lights always on' solution has hit prod. Hopefully it helps you and your team. Let us know if there are any pain points
