### ISSUE TITLE
Strike through markdown syntax works in Nucleus preview but it not rendered on mozilla.org

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/nucleus#665]
In nucleus, using ~~ signs to delimit a note that is stroken through does work in preview, but once rendered on mozilla.org, this is not translated as html and the ~~ marks are rendered instead.
I ended up using a real `<strike>` tag.

It would be nice to have this markdown syntax either rendered on mozilla.org or disabled in Nucleus.

Thanks

**Comment by stevejalim** [comment]
At a guess our Markdown allowlist in Bedrock doesn't include strikethrough as an option. Will have a look now

**Comment by stevejalim** [comment]
Hmm - apparently it _does_ allow it on the Bedrock side (https://github.com/mozilla/bedrock/blob/673da9818d76617917fda62bec26224cc6f6cef5/bedrock/contentful/templatetags/helpers.py#L10) so i'll check deeper what's happening in Nucleus (and also double-check what Bedrock is expecting as Markdown syntax for strikethrough)

**Comment by stevejalim** [comment]
Ah looks like releasenotes generates a <del>, which is not in the allowlist for our HTML cleaning. Will add it now

**Comment by stevejalim** [comment]
Ah, even with it allowed, we don't get that far, because `~~test~~` isn't converted by Python-Markdown https://github.com/Python-Markdown/markdown/issues/221

I'll take a swing at a custom processor to handle it

**Comment by pmac** [comment]
Wild that it's not supported out of the box in the Markdown library.

**Comment by stevejalim** [comment]
@pascalchevrel Bonne année! The fix is merged and should hit prod in the next 48ish hours - https://whatsdeployed.io/s/RuO/mozilla/bedrock

**Comment by pascalchevrel** [comment]
Thanks!
