### ISSUE TITLE
Improve release changelist view to show whether a release is live

### ISSUE THREAD

**Issue by stevejalim** [mozilla/nucleus#781]
Draft issue - notes:

It would be useful if release notes editors using Nucleus had a way to see whether a release was now live on Bedrock. 

However we determine this, it would be good to show it in an admin changelist/list-view column.

**Comment by stevejalim** [comment]
@pascalchevrel when you have time, could you let me know a clearer definition of what 'live' means? I didn't capture it in my meeting notes

**Comment by pascalchevrel** [comment]
I meant that the release notes page content is live and users can see it. We often load the release notes repeatedly to see the changes live.
