### ISSUE TITLE
Add a Review Checkbox on Release pages

### ISSUE THREAD

**Issue by DonalMe** [mozilla/nucleus#788]
Relman peer review release notes. 
It would be useful to have a checkbox that relman can check to indicate they reviewed a specific release

**Comment by stevejalim** [comment]
Hi @DonalMe should there be any behaviour attached to the status of the checkbox, or is it purely a sign a visual indication that review happened?

**Comment by DonalMe** [comment]
Hi @stevejalim thanks for the follow-up. 
" purely a sign a visual indication that review happened" - Correct, just an indicator that there was a review
