### ISSUE TITLE
Add data models for bedrock page content cards

### ISSUE THREAD

**Issue by pmac** [mozilla/nucleus#87]
See [bedrock content cards docs](https://www-admin.readthedocs.io/) for current data structure.

**Comment by mastizada** [comment]
> The data in each file can really be any YAML you want

Also the way they handle image url is a bit strange.

So, In my understanding, idea is to fetch files from [git repo](https://github.com/mozmeao/www-admin/tree/master/content) and then parse them to store in django models (a bedrock's macro parse can be used too.

Can you describe how it will be used?
