### ISSUE TITLE
Update HostnameMiddleware for k8s

### ISSUE THREAD

**Issue by jpetto** [mozilla/nucleus#98]
[Current HostnameMiddleware](https://github.com/mozilla/nucleus/blob/80195d10ca2d7abae44d86d3949b3cb4a6bae956/nucleus/base/middleware.py#L8) references Deis settings - we need to replace these with k8s equivalents in order to migrate off Deis.

Possible replacements (though I'm not sure what k8s environment variables are available):

DEIS_APP : k8s namespace
DEIS_RELEASE : k8s version
DEIS_DOMAIN: k8s pod

**Comment by jgmize** [comment]
Fixed in #100
